VAR:    
    BSUB_QUEUE: normal
    DEFAULT_PATH: ${CWD}/${BLOCK}/${VERSION}
TASK:
    prepare_database:
        RUN:
            PATH: ${DEFAULT_PATH}/dv
            COMMAND: mkdir -p ${DEFAULT_PATH}/dv;cp -r ${DEMO_PATH}/DV/* ${DEFAULT_PATH}/dv
    dut:
        RUN:
            PATH: ${DEFAULT_PATH}/dv/verif/sim/
            COMMAND:  source ${DEFAULT_PATH}/dv/verif/sim/setup.sh;make dut
            RUN_METHOD: bsub -q ${BSUB_QUEUE} -Is
        RUN_AFTER:
            TASK: prepare_database
        DEPENDENCY:
            FILE:
                - ${DEFAULT_PATH}/dv/verif/sim/setup.sh
    uvm:
        RUN:
            PATH: ${DEFAULT_PATH}/dv/verif/sim/
            COMMAND: source ${DEFAULT_PATH}/dv/verif/sim/setup.sh;make uvm
            RUN_METHOD: bsub -q ${BSUB_QUEUE} -Is
        RUN_AFTER:
            TASK: dut
    testbench:
        RUN:
            PATH: ${DEFAULT_PATH}/dv/verif/sim/
            COMMAND: source ${DEFAULT_PATH}/dv/verif/sim/setup.sh;make testbench
            RUN_METHOD: bsub -q ${BSUB_QUEUE} -Is
        RUN_AFTER:
            TASK: uvm
    elab:
        RUN:
            PATH: ${DEFAULT_PATH}/dv/verif/sim/
            COMMAND: source ${DEFAULT_PATH}/dv/verif/sim/setup.sh;make elab
            RUN_METHOD: bsub -q ${BSUB_QUEUE} -Is
        RUN_AFTER:
            TASK: testbench
    simv:
        RUN:
            PATH: ${DEFAULT_PATH}/dv/verif/sim/
            COMMAND: source ${DEFAULT_PATH}/dv/verif/sim/setup.sh;make simv
            RUN_METHOD: bsub -q ${BSUB_QUEUE} -Is
        RUN_AFTER:
            TASK: elab

FLOW:
    initial: [prepare_database]
    analysis: [dut, uvm, testbench]
    elaboration: [elab]
    simulation: [simv]
