## Format ##
# VAR:
#     key: value
#
# TASK:
#     flow(RUN_AFTER=):vendor:task(RUN_AFTER=):
#         action:
#             attribute: value
#    
#
## Supported Variables (default) ##
# CWD: <ifp start directory>
# IFP_INSTALL_PATH: <ifp install path>
# BLOCK: <block name>
# VERSION: <version name>
# FLOW: <flow name>
# VENDOR: <vendor name>
# BRANCH: <branch name>
# TASK: <task name>
#
#
## Supported action ##
# BUILD/RUN/CHECK/SUMMARIZE/POST_RUN/RELEASE
# 
# 
## Supportedd action attribute ##
# PATH/COMMAND/RUN_METHOD/VIEWER/REPORT_FILE
#
#
## Example ##
# VAR:
#     BSUB_QUEUE: ai_syn
#     DEFAULT_PATH: ${CWD}/${BLOCK}/${VERSION}/${FLOW}/${VENDOR}/${BRANCH}
#
# TASK:
#    k_lib:cadence:setup:
#        RUN:
#            PATH: ${DEFAULT_PATH}
#            COMMAND: ${LIBRARY_CHARACTERIZATION}/tools/gen_setup_file.py -i ${DEFAULT_PATH}/customized_ip_spec_${BLOCK}_${VERSION}_kg_${BRANCH}.xlsx -s kg
#            RUN_METHOD: bsub -q ${BSUB_QUEUE}
#        CHECK:
#            PATH: ${DEFAULT_PATH}
#            COMMAND: ${LIBRARY_CHARACTERIZATION}/tools/pre_check.py -i ${DEFAULT_PATH}/kitgen_setup.txt -s kg
#            RUN_METHOD: bsub -q ${BSUB_QUEUE}
#    k_lib:cadence:lpe(RUN_AFTER=setup):
#        RUN:
#            PATH: ${DEFAULT_PATH}
#            COMMAND: ${LIBRARY_CHARACTERIZATION}/tools/gen_lpe.py -i ${DEFAULT_PATH}/kitgen_setup.txt -s kg
#            RUN_METHOD: bsub -q ${BSUB_QUEUE}

